spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/database?schema=app
    username: root
    password: 123456
    # config from https://github.com/r2dbc/r2dbc-pool
    pool:
      initial-size: 10
      max-size: 100
      max-idle-time: 30m
logging:
  level:
    org.epha.r2dbc: debug
    org.springframework.data.r2dbc: debug

